#!/bin/bash

input_file="caminho/para/o/script.sql"
temp_file=$(mktemp)

sed '1,7 s/^/-- /' "$input_file" > "$temp_file"

mv "$temp_file" "$input_file"

echo "As sete primeiras linhas do arquivo foram comentadas."
