#!/bin/bash

# Obter o nome do branch atual
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Definir a variável de ambiente BRANCH_NAME
export BRANCH_NAME="$current_branch"

sed "s/@branch_name/$BRANCH_NAME/g" src/script.sql

docker exec -i mysql mysql -u root -p123456 < script.sql