#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)


echo "Diretório: ../src/"
ls -l src/

# Usando find para procurar arquivos .sql no diretório
#find src -type f -name "*.sql" | while read -r file; do
#    if [ -f "$file" ]; then
#        # Faça alguma coisa com o arquivo
#        echo "Arquivo SQL encontrado: $file"
#    else
#        echo "Arquivo SQL não encontrado: $file"
#    fi
#done

find src -type f -name "*.sql" | while read -r file; do
  if [ -f "$file" ]; then
    if [ "$branch" = "refs/head/dev" ]; then
        sed -i "s/dlh-prd-brlm-zcb/dlh-dev-brlm-qr8/g" "$file"
    elif [ "$branch" = "refs/head/prod" ]; then
        sed -i "s/dlh-dev-brlm-qr8/dlh-prd-brlm-zcb/g" "$file"
    fi
  fi

done
