#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

for file in src/*; do
  if [ -f "$file" ]; then
    if [ "$branch" = "refs/head/dev" ]; then
        sed -i "s/dlh-prd-brlm-zcb/dlh-dev-brlm-qr8/g" "$file"
    elif [ "$branch" = "refs/head/prod" ]; then
        sed -i "s/dlh-dev-brlm-qr8/dlh-prd-brlm-zcb/g" "$file"
    fi
  fi
done
