name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:

      - name: Carregar arquivo de ambiente
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Run MySQL container
        run: |
          docker run -d --name mysql-container -e MYSQL_ROOT_PASSWORD=123456 mysql:latest

      - name: sleep 10 seconds
        run: |
          sleep 10

      - name: verificar containers
        run:   docker ps
    
      - name: Copy script to MySQL container
        run: docker cp src/script.sql mysql-container:/src
  
      - name: Execute script in MySQL container
        run: |
          docker exec -i mysql-container mysql -u root -p123456 < src/script.sql 

      
      
      
      