name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:

      - name: Carregar arquivo de ambiente
        uses: actions/checkout@v2
        with:
          path: env_file.env

      - name: Obter nome da branch
        run: echo "O nome da branch é ${GITHUB_REF#refs/heads/}"

      