name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SQL script to print variable
        run: |
          cat script.sql
