name: Automatizar Atualização de Strings

on:
  push:
    branches:
      - dev
      - prod

jobs:
  update_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2
      
      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y sed

      - name: Executar Script Bash
        run: |
          bash src/script.sh

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

