name: Automatizar Atualização de Strings

on:
  push:
    branches:
      - dev
      - prod

jobs:
  update_strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2
      
      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y sed
      
      - name: set config git
        run: |
          git config user.email "leonardo.paixao@wolkedatasolutions.com"
          git config user.name "wolke-leonardo-paixao"

      - name: Executar Script Bash
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)

          # Verificar se estamos em uma branch de interesse
          if [ "$branch" != "dev" ] && [ "$branch" != "prod" ]; then
              echo "Este script só pode ser executado nas branches 'dev' ou 'prod'."
              exit 1
          fi
        
          # Encontrar diretórios e arquivos
          find src -type f -name "*.sql" | while read -r file; do
              if [ -f "$file" ]; then
                  if [ "$branch" = "dev" ]; then
                      sed -i "s/dlh-prd-brlm-zcb/dlh-dev-brlm-qr8/g" "$file"
                  elif [ "$branch" = "prod" ]; then
                      sed -i "s/dlh-dev-brlm-qr8/dlh-prd-brlm-zcb/g" "$file"
                  fi
                  git add "$file"
              fi
          done
        
          # Adicionar e fazer o commit das alterações
          git commit -m "Atualizar strings SQL para a branch $branch"    
          git push origin "$branch"    

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

