name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Carregar arquivo de ambiente
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Determine view name
        id: view_name
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [[ $current_branch == "dev" ]]; then
            echo "dlh-dev-brlm-qr8"
          elif [[ $current_branch == "prod" ]]; then
            echo "dlh-prd-brlm-zcb"
          else
            echo "Branch desconhecida."
          fi

      - name: Set view name as environment variable
        run: |
          echo "VIEW_NAME=$(echo "${{ steps.view_name.outputs.stdout }}")" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Run MySQL container
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest

      - name: Sleep for 60 seconds
        run: sleep 60
    
      - name: Copy script to MySQL container
        run: docker cp src mysql-container:/src  

      - name: Copy repository to MySQL container
        run: docker cp .git mysql-container:/.git      
      
      - name: verificar containers
        run:  docker ps
  
      - name: Execute script in MySQL container
        run: |
          docker exec -i mysql mysql -u root -p123456 -e "SET @view_name='${{ env.VIEW_NAME }}'; source src/script.sql"
