name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    services:
          mysql:
            image: mysql:8.0
            env:
              MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
              MYSQL_DATABASE: ${{ secrets.DB_NAME }}
              MYSQL_USER: ${{ secrets.DB_USER }}
              MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
        - name: Checkout do código
          uses: actions/checkout@v2
    
        - name: Esperar pelo MySQL estar pronto
          run: |
            docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' de6f1e116190
    
        - name: Executar testes SQL
          run: mysql -h 88bbf6ff5f2142aa8f23f31dd55f002d_mysql80_bef837 -P 3306 -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_ROOT_PASSWORD }}" < script.sql
    