name: Print variable from SQL script

on:
  push:
    branches:
      - 'prod'
      - 'dev'

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Carregar arquivo de ambiente
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Run MySQL container
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest

      - name: Sleep for 15 seconds
        run: sleep 15
    
      - name: Copy script to MySQL container
        run: docker cp src mysql-container:/src  

      - name: Copy repository to MySQL container
        run: docker cp .git mysql-container:/.git      
      
      - name: verificar containers
        run:  docker ps
  
      - name: Execute script in MySQL container
        run: |
          docker exec -i mysql-container mysql -u root -p123456 < src/script.sql
