name: replace projectId
 
on:
  push:
    branches:
      - 'prod'
      - 'dev'
 
jobs:
  print-variable:
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Carregar arquivo de ambiente
        uses: actions/checkout@v2
 
      - name: Get Branch Name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')" >> $GITHUB_ENV
 
      - name: Update script SQL with branch name
        run: |
          find src -type f -name "*" | while read -r file; do
          if [ -f "$file" ]; then
            if [ "$BRANCH_NAME" = "dev" ]; then
              sed -i "s/dlh-prd-brlm-zcb/dlh-dev-brlm-qr8/g" "$file"
            elif [ "$BRANCH_NAME" = "prod" ]; then
              sed -i "s/dlh-dev-brlm-qr8/dlh-prd-brlm-zcb/g" "$file"
            fi
          else
            echo "arquivo não encotrado"
          fi
